### ISSUE TITLE
Unirest not working, conflicts with addressable

### ISSUE THREAD

**Issue by dodops** [Kong/unirest-ruby#33]
Hi guys!

I'm trying to use Unirest but I get an error:

`'raise_if_conflicts': Unable to activate unirest-1.1.2, because addressable-2.4.0 conflicts with addressable (~> 2.3.5) (Gem::ConflictError)`

Looks like there's a conflict with the version of addressable. How can I fix this?

**Comment by paulmakepeace** [comment]
This should fix it: https://github.com/Mashape/unirest-ruby/pull/40
